[project]
name = "parcialsi1"
version = "0.1.0"
description = "Parcial 1 - Sistemas Inteligentes II + Introducción al Deep Learning: implementación de Perceptrón de Rosenblatt y ADALINE"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
]

[tool.uv]
package = false

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "pytest>=9.1.1",
    "ruff>=0.16.6",
]